### ISSUE TITLE
Speech recognition fail on IOS

### ISSUE THREAD

**Issue by syedareebshah** [capacitor-community/speech-recognition#69]
**Describe the bug**
I am trying to add speech recognition in my ionic react capacitor app. Working fine on Android. But a promise is failing on ios. please guide.
When I hit this function in IOS, it goes into catch block.

error: {errorMessage: "Ongoing speech recognition", message: "Ongoing speech recognition"}

const handleVoice = async () => {
    try {
      let result = await SpeechRecognition.start({
        language: "en-US",
        maxResults: 2,
        prompt: "Say something",
        partialResults: true,
        popup: true,
      });
      const speechResult = result?.matches[0];
      setTranscript(speechResult);
      console.log("==>", speechResult);
    } catch (error) {
      alert("Plz try again");
    }
  };

**To Reproduce**
clone=> https://github.com/areeb-gsoftconsulting/ionic-learn
branch name=>[speech-recognition](https://github.com/areeb-gsoftconsulting/ionic-learn/tree/speech-recognition)

run this app and try speech recognition.

**Smartphone (please complete the following information):**
 - Device: IPhone X

**Comment by jcesarmobile** [comment]
Your app is working fine, but if you use `partialResults: true` then the result won't be available by awaiting `start()`, in that case you have to use 
```
SpeechRecognition.addListener("partialResults", (data: any) => {
  console.log("partialResults was fired", data.matches);
});
```
If you change to `partialResults: false` you should get the result on the await.

The "Ongoing speech recognition" error happens when you call start while the speech recognizer is already listening, so maybe you are clicking twice?

Also noticed that your sample app uses Capacitor 4 but you have several Capacitor 5 plugins installed, you should use the same version that matches your Capacitor version.
